@startuml

title 勤怠管理システム

[*] --> ログイン画面
ログイン画面 --> スタート画面: ユーザ名，パスワード入力
スタート画面 --> 終了画面: 出勤状態
終了画面 --> 編集画面: ユーザの出退勤データ編集
スタート画面 --> 編集画面: ユーザの出退勤データ編集
終了画面 --> [*]

note left of ログイン画面 : ログイン
note left of スタート画面 : 出勤
note left of 終了画面 : 退勤
note left of 編集画面 : 出退勤の編集および削除

@enduml